@API_URL = http://localhost:5500

###

POST http://localhost:5500/auth/register
Content-Type: application/json

{
    "email":"santhoshm2504@gmail.com",
    "name":"dev1",
    "Dob":"30-10-2001",
    "profileImgUrl":"helloworld",
    "github":"tubelight056",
    "devto": "devtoLink",
    "medium":"medium link",
    "skills":["js","python","java"],
    "education":[{ "Degree": "BE",
      "Institution":"CIT",
      "StartYear": 2019,
      "EndYear": 2023}],
      "experience":[{
          "companyName":"Cadra",
          "duration": 3,
          "position": "Backend",
          "description": "hai"
        },{
          "companyName":"Cadra",
          "duration": 3,
          "position": "Backend",
          "description": "hai"
        },{
          "companyName":"Cadra",
          "duration": 3,
          "position": "Backend"
        }],
        "Location":"12.000 13.0000"
}

###

POST {{API_URL}}/auth/login
Content-Type: application/json

{
    "email":"viratsando@gmail.com"
}

###
POST  {{API_URL}}/get/alldetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2YyYWYyYTA0NDc1ZDQzZDhhYzlmYyIsIk5hbWUiOiJkZXYxIiwiRW1haWwiOiJ0dWJlbGlnaHRib3kwNTZAZ21haWwuY29tIiwiaWF0IjoxNjQ4MzA3MDMxLCJleHAiOjE2NDg0NTEwMzF9.qU6TaVMu_GDzjsBofgVE4eRDRYHx9-6HOdXakZwLQ50

###
POST  {{API_URL}}/get/user/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjZkNGQ0MmVkNDFjMGI2NDcwYWRhZCIsIk5hbWUiOiJkZXYxIiwiRW1haWwiOiJ0dWJlbGlnaHRib3kwNTZAZ21haWwuY29tIiwiaWF0IjoxNjQ2ODE1MDM3LCJleHAiOjE2NDY5NTkwMzd9.UTsvzpLL4yWJQHMXHoVn-g_CT_H8qXPK-n4z5VC1zME
Content-Type: application/json

{
  "skills":["js"]
}

###
POST  {{API_URL}}/project/user/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY0OTU2ODU2NSwiZXhwIjoxNjQ5NzEyNTY1fQ.jHWqNKmgTFzPpvf5lPXiLUx66OBy4jY31RPvn20YR7k
Content-Type: application/json

{
    "tags":[ "project" ],
    "Github_id":384906199
}

###
POST  {{API_URL}}/project/user/gitrepo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2YyYWYyYTA0NDc1ZDQzZDhhYzlmYyIsIk5hbWUiOiJkZXYxIiwiRW1haWwiOiJ0dWJlbGlnaHRib3kwNTZAZ21haWwuY29tIiwiaWF0IjoxNjQ4MzA3MDMxLCJleHAiOjE2NDg0NTEwMzF9.qU6TaVMu_GDzjsBofgVE4eRDRYHx9-6HOdXakZwLQ50



###
POST  {{API_URL}}/project/user/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY0OTQ4MTc2NiwiZXhwIjoxNjQ5NjI1NzY2fQ.JVgm2XZ3Au9PTC94DDG1sCt1a54h-yHTGzecMhzi0TM
Content-Type: application/json

{
    "search":"My"
}

### 
POST  {{API_URL}}/get/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY0OTQ4MTc2NiwiZXhwIjoxNjQ5NjI1NzY2fQ.JVgm2XZ3Au9PTC94DDG1sCt1a54h-yHTGzecMhzi0TM
Content-Type: application/json

{
}

###

POST  {{API_URL}}/blog/user/devto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY0OTQ4MTc2NiwiZXhwIjoxNjQ5NjI1NzY2fQ.JVgm2XZ3Au9PTC94DDG1sCt1a54h-yHTGzecMhzi0TM


###

POST  {{API_URL}}/blog/user/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY0OTQ4MTc2NiwiZXhwIjoxNjQ5NjI1NzY2fQ.JVgm2XZ3Au9PTC94DDG1sCt1a54h-yHTGzecMhzi0TM
Content-Type: application/json

{
    "Blog_id":1045920
}

###

POST  {{API_URL}}/blog/user/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY0OTQ4MTc2NiwiZXhwIjoxNjQ5NjI1NzY2fQ.JVgm2XZ3Au9PTC94DDG1sCt1a54h-yHTGzecMhzi0TM
Content-Type: application/json

{
    "search":"My"
}

###
POST  {{API_URL}}/get/score
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY1MDEyOTE2OSwiZXhwIjoxNjUwMjczMTY5fQ._vbdqerECAytpexIWRY2G2iVuElsX5g3c--psVkX8w4
Content-Type: application/json

{
  "id":"62483837cefdf358826d9eae"
}

###
POST  {{API_URL}}/get/user/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDgzODM3Y2VmZGYzNTg4MjZkOWVhZSIsIk5hbWUiOiJkZXYyIiwiRW1haWwiOiJ2aXJhdHNhbmRvQGdtYWlsLmNvbSIsImlhdCI6MTY1MDEyOTE2OSwiZXhwIjoxNjUwMjczMTY5fQ._vbdqerECAytpexIWRY2G2iVuElsX5g3c--psVkX8w4
Content-Type: application/json

{
  "id":"62483837cefdf358826d9eae"
}