@API_URL = http://localhost:5500

###

POST http://localhost:5500/auth/register
Content-Type: application/json
{
    "email":"tubelightboy056@gmail.com",
    "name":"dev1",
    "Dob":"30-10-2001",
    "profileImgUrl":"helloworld",
    "Github":"hai",
      "devto": "devtoLink",
      "medium":"medium link",
      "skills":["js","python","java"],
       "education":[{
      "name": "school",
      "year": "2001"
    },{
      "name": "school",
      "year": "2001"
    },{
      "name": "school",
      "year": "2001"
    }],
      "experience":[{
          "companyName":"Cadra",
          "duration": 3,
          "position": "Backend",
          "description": "hai"
        },{
          "companyName":"Cadra",
          "duration": 3,
          "position": "Backend",
          "description": "hai"
        },{
          "companyName":"Cadra",
          "duration": 3,
          "position": "Backend"
        }],
        "Location":"12.000 13.0000"
}

###
POST {{API_URL}}/auth/login
Content-Type: application/json

{
    "email":"tubelightboy056@gmail.com"
}

###
POST  {{API_URL}}/get/alldetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjZkNGQ0MmVkNDFjMGI2NDcwYWRhZCIsIk5hbWUiOiJkZXYxIiwiRW1haWwiOiJ0dWJlbGlnaHRib3kwNTZAZ21haWwuY29tIiwiaWF0IjoxNjQ2ODE1MDM3LCJleHAiOjE2NDY5NTkwMzd9.UTsvzpLL4yWJQHMXHoVn-g_CT_H8qXPK-n4z5VC1zME

###
POST  {{API_URL}}/get/user/skills
Authorization: Bearer 
Content-Type: application/json

{
  "skills":["js"]
}